### ISSUE TITLE
Wrong characters - brackets

### ISSUE THREAD

**Issue by hundera** [Angelelz/ClipboardPlaceholder#1]
Hi, 
it's great plugin. But there's a little problem, when text contains brackets.

If text contains (), bracket are omitted. If text contains {}, autotypes failed.

thanks.

**Comment by Angelelz** [comment]
Thank you for reporting. Those are limitations of autotype itself (ie: KeePass), It has nothing to do with the plug in. It has to do with the way placeholders work. See https://keepass.info/help/base/placeholders.html for reference

**Comment by hundera** [comment]
Thanks for replay. 
I hoped, that brackets "(" just can be replaced with "{(}" before printing clipboard. This way it can be used with autotype. (https://keepass.info/help/base/autotype.html#autoseq)

If brackets are used in any field (eg. notes), it's printed correctly with placemark {notes}. So I thought that it can be used in custom plugin too.

**Comment by Angelelz** [comment]
That could be a way to allow this feature, but it would require some logic in place to detect when you have any "(" or ")" in the clipboard text. Unfortunately I've been very busy lately, so that could take some time. I'll leave this issue opened and maybe work on this later

**Comment by hundera** [comment]
Thanks! Now its perfect.

**Comment by Angelelz** [comment]
Just so you know, I asked for this feature a couple month ago, but it will be implemented in KeePass. See: https://sourceforge.net/p/keepass/discussion/329220/thread/7635526ba5/?limit=25#e1cf for more info
